export default [
  {
    code: 'Backquote',
    controlKey: false,
    ru: 'ё',
    eng: '`',
    ru_add: null,
    eng_add: '~',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit1',
    controlKey: false,
    ru: '1',
    eng: '1',
    ru_add: '!',
    eng_add: '!',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit2',
    controlKey: false,
    ru: '2',
    eng: '2',
    ru_add: '"',
    eng_add: '@',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit3',
    controlKey: false,
    ru: '3',
    eng: '3',
    ru_add: '№',
    eng_add: '#',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit4',
    controlKey: false,
    ru: '4',
    eng: '4',
    ru_add: ';',
    eng_add: '$',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit5',
    controlKey: false,
    ru: '5',
    eng: '5',
    ru_add: '%',
    eng_add: '%',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit6',
    controlKey: false,
    ru: '6',
    eng: '6',
    ru_add: ':',
    eng_add: '^',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit7',
    controlKey: false,
    ru: '7',
    eng: '7',
    ru_add: '?',
    eng_add: '&',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit8',
    controlKey: false,
    ru: '8',
    eng: '8',
    ru_add: '*',
    eng_add: '*',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit9',
    controlKey: false,
    ru: '9',
    eng: '9',
    ru_add: '(',
    eng_add: '(',
    classes: ['key', 'letter'],
  },
  {
    code: 'Digit0',
    controlKey: false,
    ru: '0',
    eng: '0',
    ru_add: ')',
    eng_add: ')',
    classes: ['key', 'letter'],
  },
  {
    code: 'Minus',
    controlKey: false,
    ru: '-',
    eng: '-',
    ru_add: '_',
    eng_add: '_',
    classes: ['key', 'letter'],
  },
  {
    code: 'Equal',
    controlKey: false,
    ru: '=',
    eng: '=',
    ru_add: '+',
    eng_add: '+',
    classes: ['key', 'letter'],
  },
  {
    code: 'Backspace',
    controlKey: true,
    ru: 'Backspace',
    eng: 'Backspace',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'backspace'],
  },
  {
    code: 'Tab',
    controlKey: true,
    ru: 'Tab',
    eng: 'Tab',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'tab'],
  },
  {
    code: 'KeyQ',
    controlKey: false,
    ru: 'й',
    eng: 'q',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyW',
    controlKey: false,
    ru: 'ц',
    eng: 'w',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyE',
    controlKey: false,
    ru: 'у',
    eng: 'e',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyR',
    controlKey: false,
    ru: 'к',
    eng: 'r',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyT',
    controlKey: false,
    ru: 'е',
    eng: 't',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyY',
    controlKey: false,
    ru: 'н',
    eng: 'y',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyU',
    controlKey: false,
    ru: 'г',
    eng: 'u',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyI',
    controlKey: false,
    ru: 'ш',
    eng: 'i',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyO',
    controlKey: false,
    ru: 'щ',
    eng: 'o',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyP',
    controlKey: false,
    ru: 'з',
    eng: 'p',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'BracketLeft',
    controlKey: false,
    ru: 'х',
    eng: '[',
    ru_add: null,
    eng_add: '{',
    classes: ['key', 'letter'],
  },
  {
    code: 'BracketRight',
    controlKey: false,
    ru: 'ъ',
    eng: ']',
    ru_add: null,
    eng_add: '}',
    classes: ['key', 'letter'],
  },
  {
    code: 'Backslash',
    controlKey: false,
    ru: '\\',
    eng: '\\',
    ru_add: '/',
    eng_add: '|',
    classes: ['key', 'letter'],
  },
  {
    code: 'Delete',
    controlKey: true,
    ru: 'Del',
    eng: 'Del',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'delete'],
  },
  {
    code: 'CapsLock',
    controlKey: true,
    ru: 'Caps Lock',
    eng: 'Caps Lock',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'caps'],
  },
  {
    code: 'KeyA',
    controlKey: false,
    ru: 'ф',
    eng: 'a',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyS',
    controlKey: false,
    ru: 'ы',
    eng: 's',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyD',
    controlKey: false,
    ru: 'в',
    eng: 'd',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyF',
    controlKey: false,
    ru: 'а',
    eng: 'f',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyG',
    controlKey: false,
    ru: 'п',
    eng: 'g',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyH',
    controlKey: false,
    ru: 'р',
    eng: 'h',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyJ',
    controlKey: false,
    ru: 'о',
    eng: 'j',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyK',
    controlKey: false,
    ru: 'л',
    eng: 'k',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyL',
    controlKey: false,
    ru: 'д',
    eng: 'l',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'Semicolon',
    controlKey: false,
    ru: 'ж',
    eng: ';',
    ru_add: null,
    eng_add: ':',
    classes: ['key', 'letter'],
  },
  {
    code: 'Quote',
    controlKey: false,
    ru: 'э',
    eng: "'",
    ru_add: null,
    eng_add: '"',
    classes: ['key', 'letter'],
  },
  {
    code: 'Enter',
    controlKey: true,
    ru: 'Enter',
    eng: 'Enter',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'enter'],
  },
  {
    code: 'ShiftLeft',
    controlKey: true,
    ru: 'Shift',
    eng: 'Shift',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'left-shift'],
  },
  {
    code: 'KeyZ',
    controlKey: false,
    ru: 'я',
    eng: 'z',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyX',
    controlKey: false,
    ru: 'ч',
    eng: 'x',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyC',
    controlKey: false,
    ru: 'с',
    eng: 'c',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyV',
    controlKey: false,
    ru: 'м',
    eng: 'v',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyB',
    controlKey: false,
    ru: 'и',
    eng: 'b',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyN',
    controlKey: false,
    ru: 'т',
    eng: 'n',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'KeyM',
    controlKey: false,
    ru: 'ь',
    eng: 'm',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'letter'],
  },
  {
    code: 'Comma',
    controlKey: false,
    ru: 'б',
    eng: ',',
    ru_add: null,
    eng_add: '<',
    classes: ['key', 'letter'],
  },
  {
    code: 'Period',
    controlKey: false,
    ru: 'ю',
    eng: '.',
    ru_add: null,
    eng_add: '>',
    classes: ['key', 'letter'],
  },
  {
    code: 'Slash',
    controlKey: false,
    ru: '.',
    eng: '/',
    ru_add: ',',
    eng_add: '?',
    classes: ['key', 'letter'],
  },
  {
    code: 'ArrowUp',
    controlKey: true,
    ru: '<i class="fa fa-solid fa-caret-up fa-2x"></i>',
    eng: '<i class="fa fa-solid fa-caret-up fa-2x"></i>',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'up-arrow'],
  },
  {
    code: 'ShiftRight',
    controlKey: true,
    ru: 'Shift',
    eng: 'Shift',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'right-shift'],
  },
  {
    code: 'ControlLeft',
    controlKey: true,
    ru: 'Ctrl',
    eng: 'Ctrl',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'left-ctrl'],
  },
  {
    code: 'MetaLeft',
    controlKey: true,
    ru: 'Win',
    eng: 'Win',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'win'],
  },
  {
    code: 'AltLeft',
    controlKey: true,
    ru: 'Alt',
    eng: 'Alt',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'left-alt'],
  },
  {
    code: 'Space',
    controlKey: true,
    ru: 'Space',
    eng: 'Space',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'space'],
  },
  {
    code: 'AltRight',
    controlKey: true,
    ru: 'Alt',
    eng: 'Alt',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'right-alt'],
  },
  {
    code: 'ControlRight',
    controlKey: true,
    ru: 'Ctrl',
    eng: 'Ctrl',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'right-ctrl'],
  },
  {
    code: 'ArrowLeft',
    controlKey: true,
    ru: '<i class="fa fa-solid fa-caret-left fa-2x"></i>',
    eng: '<i class="fa fa-solid fa-caret-left fa-2x"></i>',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'left-arrow'],
  },
  {
    code: 'ArrowDown',
    controlKey: true,
    ru: '<i class="fa fa-solid fa-caret-down fa-2x"></i>',
    eng: '<i class="fa fa-solid fa-caret-down fa-2x"></i>',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'down-arrow'],
  },
  {
    code: 'ArrowRight',
    controlKey: true,
    ru: '<i class="fa fa-solid fa-caret-right fa-2x"></i>',
    eng: '<i class="fa fa-solid fa-caret-right fa-2x"></i>',
    ru_add: null,
    eng_add: null,
    classes: ['key', 'right-arrow'],
  },
];
