const KEYS = [
  {
    ru: "ё",
    eng: "`",
    ru_add: null,
    eng_add: "~",
    classes: ["key", "letter"],
  },
  {
    ru: "1",
    eng: "1",
    ru_add: "!",
    eng_add: "!",
    classes: ["key", "letter"],
  },
  {
    ru: "2",
    eng: "2",
    ru_add: "\"",
    eng_add: "@",
    classes: ["key", "letter"],
  },
  {
    ru: "3",
    eng: "3",
    ru_add: "№",
    eng_add: "#",
    classes: ["key", "letter"],
  },
  {
    ru: "4",
    eng: "4",
    ru_add: ";",
    eng_add: "$",
    classes: ["key", "letter"],
  },
  {
    ru: "5",
    eng: "5",
    ru_add: "%",
    eng_add: "%",
    classes: ["key", "letter"],
  },
  {
    ru: "6",
    eng: "6",
    ru_add: ":",
    eng_add: "^",
    classes: ["key", "letter"],
  },
  {
    ru: "7",
    eng: "7",
    ru_add: "?",
    eng_add: "&",
    classes: ["key", "letter"],
  },
  {
    ru: "8",
    eng: "8",
    ru_add: "*",
    eng_add: "*",
    classes: ["key", "letter"],
  },
  {
    ru: "9",
    eng: "9",
    ru_add: "(",
    eng_add: "(",
    classes: ["key", "letter"],
  },
  {
    ru: "0",
    eng: "0",
    ru_add: ")",
    eng_add: ")",
    classes: ["key", "letter"],
  },
  {
    ru: "-",
    eng: "-",
    ru_add: "_",
    eng_add: "_",
    classes: ["key", "letter"],
  },
  {
    ru: "=",
    eng: "=",
    ru_add: "+",
    eng_add: "+",
    classes: ["key", "letter"],
  },
  {
    ru: "Backspace",
    eng: "Backspace",
    ru_add: null,
    eng_add: null,
    classes: ["key", "backspace"],
  },
  {
    ru: "Tab",
    eng: "Tab",
    ru_add: null,
    eng_add: null,
    classes: ["key", "tab"],
  },
  {
    ru: "й",
    eng: "q",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "ц",
    eng: "w",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "у",
    eng: "e",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "к",
    eng: "r",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "е",
    eng: "t",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "н",
    eng: "y",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "г",
    eng: "u",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "ш",
    eng: "i",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "щ",
    eng: "o",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "з",
    eng: "p",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "х",
    eng: "[",
    ru_add: null,
    eng_add: "{",
    classes: ["key", "letter"],
  },
  {
    ru: "ъ",
    eng: "]",
    ru_add: null,
    eng_add: "}",
    classes: ["key", "letter"],
  },
  {
    ru: "\\",
    eng: "\\",
    ru_add: "/",
    eng_add: "|",
    classes: ["key", "letter"],
  },
  {
    ru: "Del",
    eng: "Del",
    ru_add: null,
    eng_add: null,
    classes: ["key", "delete"],
  },
  {
    ru: "Caps Lock",
    eng: "Caps Lock",
    ru_add: null,
    eng_add: null,
    classes: ["key", "caps"],
  },
  {
    ru: "ф",
    eng: "a",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "ы",
    eng: "s",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "в",
    eng: "d",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "а",
    eng: "f",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "п",
    eng: "g",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "р",
    eng: "h",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "о",
    eng: "j",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "л",
    eng: "k",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "д",
    eng: "l",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "ж",
    eng: ";",
    ru_add: null,
    eng_add: ":",
    classes: ["key", "letter"],
  },
  {
    ru: "э",
    eng: "'",
    ru_add: null,
    eng_add: "\"",
    classes: ["key", "letter"],
  },
  {
    ru: "Enter",
    eng: "Enter",
    ru_add: null,
    eng_add: null,
    classes: ["key", "enter"],
  },
  {
    ru: "Shift",
    eng: "Shift",
    ru_add: null,
    eng_add: null,
    classes: ["key", "left-shift"],
  },
  {
    ru: "\\",
    eng: "\\",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "я",
    eng: "z",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "ч",
    eng: "x",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "с",
    eng: "c",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "м",
    eng: "v",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "и",
    eng: "b",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "т",
    eng: "n",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "ь",
    eng: "m",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "б",
    eng: ",",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "ю",
    eng: ".",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "/",
    eng: "/",
    ru_add: null,
    eng_add: null,
    classes: ["key", "letter"],
  },
  {
    ru: "<i class=\"fa fa-solid fa-caret-up fa-2x\"></i>",
    eng: "<i class=\"fa fa-solid fa-caret-up fa-2x\"></i>",
    ru_add: null,
    eng_add: null,
    classes: ["key", "up-arrow"],
  },
  {
    ru: "Shift",
    eng: "Shift",
    ru_add: null,
    eng_add: null,
    classes: ["key", "right-shift"],
  },
  {
    ru: "Ctrl",
    eng: "Ctrl",
    ru_add: null,
    eng_add: null,
    classes: ["key", "left-ctrl"],
  },
  {
    ru: "Win",
    eng: "Win",
    ru_add: null,
    eng_add: null,
    classes: ["key", "win"],
  },
  {
    ru: "Alt",
    eng: "Alt",
    ru_add: null,
    eng_add: null,
    classes: ["key", "left-alt"],
  },
  {
    ru: "Space",
    eng: "Space",
    ru_add: null,
    eng_add: null,
    classes: ["key", "space"],
  },
  {
    ru: "Alt",
    eng: "Alt",
    ru_add: null,
    eng_add: null,
    classes: ["key", "right-alt"],
  },
  {
    ru: "Ctrl",
    eng: "Ctrl",
    ru_add: null,
    eng_add: null,
    classes: ["key", "right-ctrl"],
  },
  {
    ru: "<i class=\"fa fa-solid fa-caret-left fa-2x\"></i>",
    eng: "<i class=\"fa fa-solid fa-caret-left fa-2x\"></i>",
    ru_add: null,
    eng_add: null,
    classes: ["key", "left-arrow"],
  },
  {
    ru: "<i class=\"fa fa-solid fa-caret-down fa-2x\"></i>",
    eng: "<i class=\"fa fa-solid fa-caret-down fa-2x\"></i>",
    ru_add: null,
    eng_add: null,
    classes: ["key", "down-arrow"],
  },
  {
    ru: "<i class=\"fa fa-solid fa-caret-right fa-2x\"></i>",
    eng: "<i class=\"fa fa-solid fa-caret-right fa-2x\"></i>",
    ru_add: null,
    eng_add: null,
    classes: ["key", "right-arrow"],
  },
];